server {
  listen 80;
  server_name localhost;
 
  root /usr/share/nginx/html;
  index index.html;
 
  error_log /var/log/nginx/error.log crit;
  access_log off;

  server_tokens off;

  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header X-XSS-Protection "1; mode=block" always;
 
  location / {
    try_files $uri $uri/ /index.html;

    add_header Cache-control "no-store, no-cache, must-revalidate" always;
  }

  location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|ogg|ogv|webm|htc|woff|woff2|tff)$ {
    expires 1y;
    access_log off;
    log_not_found off;
    add_header Cache-Control "public, immutable" always;
  }

  location ~ /\. {
    deny all;
    access_log off;
    log_not_found off;
  }

}
