name: kinsfolk

x-frontend-base-build: &frontend-base-build
  context: ./frontEnd
  dockerfile: Dockerfile
  args:
    NODE_VERSION: ${NODE_VERSION}

x-frontend-base: &frontend-base
  env_file:
    - ./.env
  restart: unless-stopped
  networks:
    - internal-nw

x-main-proxy-base: &main-proxy-base
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
    - extenal-nw
    - internal-nw

x-backend-base: &backend-base
    build:
      context: ./backEnd
      dockerfile: Dockerfile
      target: backend-production
      args:
        NODE_VERSION: ${NODE_VERSION}
    restart: unless-stopped
    networks:
      - internal-nw

services:

  main-proxy:
    container_name: main-proxy
    profiles: ["prod"]
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    <<: *main-proxy-base
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx_cache:/tmp/nginx_cache
    depends_on:
      - backend

  backend:
    profiles: ["prod"]
    container_name: backend
    volumes:
      - backend_db:/app/db
    <<: *backend-base

  main-proxy-dev:
    container_name: main-proxy-dev
    profiles: ["dev"]
    image: nginx:alpine
    ports:
      - 8080:80
    <<: *main-proxy-base
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx_cache_dev:/tmp/nginx_cache
    depends_on:
      - frontend-dev
      - backend-dev

  backend-dev:
    profiles: ["dev"]
    container_name: backend-dev
    volumes:
      - backend_db_dev:/app/db
    <<: *backend-base

  frontend-dev:
    profiles: ["dev"]
    build:
      <<: *frontend-base-build
      target: development
    container_name: page-dev
    ports:
        - "5173:5173"
    volumes:
      - ./frontEnd:/app
      - frontend_node_modules:/app/node_modules
    <<: *frontend-base
    depends_on:
      - backend-dev
    networks:
      - extenal-nw

  ngrok-tunnel:
    profiles: ["prod"]
    image: ngrok/ngrok:alpine
    container_name: tunnel
    restart: unless-stopped
    command:
      - "http"
      - "main-proxy:80"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    depends_on:
      - main-proxy
    networks:
      - extenal-nw

volumes:
  nginx_cache_dev:
    driver: local
  nginx_cache:
    driver: local
  backend_db:
  backend_db_dev:
  frontend_node_modules:

networks:
  extenal-nw:
    driver: bridge
  internal-nw:
    driver: bridge
    internal: true
