name: family-page

services:
  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
      target: ${BUILD_TARGET}
      args:
        NODE_VERSION: ${NODE_VERSION}
        BUILD_TARGET: ${BUILD_TARGET}
    ports:
        - "5173:5173"
        - "${EXTERNAL_PORT_FD}:3000"
    restart: unless-stopped
    env_file:
      - ./.env

