name: kinsfolk

x-frontend-base-build: &frontend-base-build
  context: ./frontEnd
  dockerfile: Dockerfile
  args:
    NODE_VERSION: ${NODE_VERSION}

x-frontend-base: &frontend-base
  env_file:
    - ./.env
  restart: unless-stopped

services:

  frontend-dev:
    profiles: ["dev"]
    build:
      <<: *frontend-base-build
      target: development
    container_name: page-dev
    ports:
        - "5173:5173"
    volumes:
      - ./frontEnd:/app
      - /app/node_modules
    <<: *frontend-base

  frontend-prod:
    profiles: ["prod"]
    build:
      <<: *frontend-base-build
      target: production
    container_name: page-prod
    ports:
        - "${EXTERNAL_PORT_FD}:80"
    <<: *frontend-base

