
location /api/ {
  set $backend_sv http://backend:3000;

  proxy_pass $backend_sv;
  proxy_http_version 1.1;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  # Deshabilitar caché
  proxy_no_cache 1;
  proxy_cache_bypass 1;
  proxy_set_header Cache-Control "no-cache, no-store, must-revalidate";
  proxy_set_header Pragma "no-cache";
  proxy_set_header Expires "0";

  proxy_set_header Connection close;
  proxy_set_header X-Accel-Buffering "no";
  keepalive_timeout 0;

  proxy_buffering off;
  proxy_buffer_size 64k;
  proxy_buffers 64 512k;
  proxy_busy_buffers_size 1024k;
  proxy_temp_file_write_size 1024k;
  client_max_body_size 60m;

  proxy_connect_timeout 30s;
  proxy_send_timeout 30s;
  proxy_read_timeout 30s;
}
