set $frontend_sv http://frontend-dev:5173;

location / {
  # Apunta directamente al contenedor de desarrollo en su puerto de Vite
  proxy_pass $frontend_sv;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection 'upgrade';
  proxy_set_header Host $host;
  proxy_cache_bypass $http_upgrade;

  add_header Cache-Control "no-cache, no-store, must-revalidate, private";
  expires -1;
}

