
location / {
  try_files $uri $uri/ /index.html;

  add_header Cache-Control "no-cache" always;
  
  keepalive_timeout 65;
  keepalive_requests 100;
}

location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|ogg|ogv|webm|htc|woff|woff2|tff)$ {
  expires 1y;
  access_log off;
  log_not_found off;
  add_header Cache-Control "public, immutable" always;

  keepalive_timeout 65;
  keepalive_requests 100;
}

location ~ /\. {
  deny all;
  access_log off;
  log_not_found off;
}
