
location ^/assets/ {
  expires 1y;
  add_header Cache-Control "public, immutable";
  add_header Vary "Accept-Encoding";

  gzip_static on;
  etag off;

  access_log off;
  log_not_found off;
}

location ^/(icons|images)/ {
  expires 30d;
  add_header Cache-Control "public, must-revalidate";
  add_header Vary "Accept-Encoding";
  gzip_static on;

  #access_log off;
  log_not_found off;
}

location ~* ^/([a-zA-Z0-9_-]+)\.(webp|png|jpg|jpeg|gif|ico|svg)$ {
  expires 30d;
  add_header Cache-Control "public, must-revalidate";
  add_header Vary "Accept-Encoding";

  access_log off;
  log_not_found off;
}

location = /favicon.ico {
  expires 30d;
  add_header Cache-Control "public, immutable";

  access_log off;
  log_not_found off;
}

location ~* ^/(admin|dashboard|profile|settings|account)/ {
  expires -1;
  add_header Cache-Control "no-cache, no-store, must-revalidate, private";
  add_header Pragma "no-cache";
  try_files $uri $uri/ /index.html;
}

location / {
  try_files $uri $uri/ /index.html;
  expires 5m;
  add_header Cache-Control "public, must-revalidate";
  add_header Vary "Accept-Encoding";
}

location ~ /\. {
  deny all;
  access_log off;
  log_not_found off;
}
